devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-US"
])

erase_simulator true

scheme "PhantomScreenshots"

output_directory "./fastlane/screenshots"

clear_previous_screenshots true 
