devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X",
  "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)"
])

languages([
  "en-US"
])

scheme "PhantomDev"

output_directory "./fastlane/screenshots"

clear_previous_screenshots true 
